In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train_df = pd.read_csv("Train.csv")
test = pd.read_csv('test.csv')
sub = pd.read_csv('SampleSubmission.csv')

In [3]:
pd.options.display.max_columns = 60

In [4]:
train_df.head()

,Applicant_ID,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field11,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field23,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field31,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field40,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,4397256.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,NaN,NaN,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,NaN,1052.0,8.0000,2.0,NaN,12.0,12.0,4.0,0.0,NaN,NaN,0.392854,2.02,0.711632,0.0,0.0,charge,NaN,1.129518,0.044335,no
1,Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,244292.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,14584.29,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,NaN,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,NaN,NaN,0.314281,8.08,0.183584,NaN,0.0,charge,349.805730,1.620483,0.322436,no
2,Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,1079864.0,NaN,NaN,0.0,16576457,22452691.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1597.5,4746.0,3164.0,60.0,15696.0,NaN,14508.0,70.0,0.6666,0.0,NaN,12.0,0.0,6.0,0.0,149.6805,NaN,0.162965,18.18,0.791136,0.0,0.0,charge,NaN,1.513370,0.011640,yes
3,Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,NaN,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,0.0,1.0,1.0,120.120,8580.00,0.00,85.800,1701.0,4014.0,2676.0,60.0,11679.0,NaN,NaN,522.0,7.8334,1.0,1.0,4.0,8.0,4.0,1.0,NaN,NaN,0.488884,2.02,0.685168,NaN,0.0,charge,89.940100,0.664452,0.082729,no
4,Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,396391.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,0.0,3.0,3.0,104.535,8360.19,10326.45,115.335,1551.0,3285.0,2190.0,60.0,19437.0,12958.0,5202.0,272.0,1.0000,0.0,0.0,24.0,2.0,24.0,0.0,150.0135,NaN,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53610 entries, 0 to 53609
Data columns (total 52 columns):
Applicant_ID      53610 non-null object
form_field1       51179 non-null float64
form_field2       49948 non-null float64
form_field3       53277 non-null float64
form_field4       53277 non-null float64
form_field5       53277 non-null float64
form_field6       40835 non-null float64
form_field7       48674 non-null float64
form_field8       40835 non-null float64
form_field9       45960 non-null float64
form_field10      53277 non-null float64
form_field11      23576 non-null float64
form_field12      44163 non-null float64
form_field13      47937 non-null float64
form_field14      53610 non-null int64
form_field15      32120 non-null float64
form_field16      41143 non-null float64
form_field17      42948 non-null float64
form_field18      43668 non-null float64
form_field19      53610 non-null float64
form_field20      53277 non-null float64
form_field21      38468 non-null float64
form_field22      34147 non-null float64
form_field23      26762 non-null float64
form_field24      40893 non-null float64
form_field25      48395 non-null float64
form_field26      46501 non-null float64
form_field27      44711 non-null float64
form_field28      53276 non-null float64
form_field29      53276 non-null float64
form_field30      29161 non-null float64
form_field31      15880 non-null float64
form_field32      48395 non-null float64
form_field33      52413 non-null float64
form_field34      53276 non-null float64
form_field35      31513 non-null float64
form_field36      51702 non-null float64
form_field37      48395 non-null float64
form_field38      53276 non-null float64
form_field39      49585 non-null float64
form_field40      11748 non-null float64
form_field41      17026 non-null float64
form_field42      52339 non-null float64
form_field43      53070 non-null float64
form_field44      48459 non-null float64
form_field45      23574 non-null float64
form_field46      38370 non-null float64
form_field47      53609 non-null object
form_field48      33678 non-null float64
form_field49      53276 non-null float64
form_field50      43058 non-null float64
default_status    53609 non-null object
dtypes: float64(48), int64(1), object(3)
memory usage: 21.3+ MB

In [6]:
train_df.isnull().sum()

Applicant_ID          0
form_field1        2431
form_field2        3662
form_field3         333
form_field4         333
form_field5         333
form_field6       12775
form_field7        4936
form_field8       12775
form_field9        7650
form_field10        333
form_field11      30034
form_field12       9447
form_field13       5673
form_field14          0
form_field15      21490
form_field16      12467
form_field17      10662
form_field18       9942
form_field19          0
form_field20        333
form_field21      15142
form_field22      19463
form_field23      26848
form_field24      12717
form_field25       5215
form_field26       7109
form_field27       8899
form_field28        334
form_field29        334
form_field30      24449
form_field31      37730
form_field32       5215
form_field33       1197
form_field34        334
form_field35      22097
form_field36       1908
form_field37       5215
form_field38        334
form_field39       4025
form_field40      41862
form_field41      36584
form_field42       1271
form_field43        540
form_field44       5151
form_field45      30036
form_field46      15240
form_field47          1
form_field48      19932
form_field49        334
form_field50      10552
default_status        1
dtype: int64

In [7]:
train_df.isnull().sum()/len(train_df)*100

Applicant_ID       0.000000
form_field1        4.534602
form_field2        6.830815
form_field3        0.621153
form_field4        0.621153
form_field5        0.621153
form_field6       23.829509
form_field7        9.207237
form_field8       23.829509
form_field9       14.269726
form_field10       0.621153
form_field11      56.023130
form_field12      17.621712
form_field13      10.581981
form_field14       0.000000
form_field15      40.085805
form_field16      23.254990
form_field17      19.888081
form_field18      18.545048
form_field19       0.000000
form_field20       0.621153
form_field21      28.244730
form_field22      36.304794
form_field23      50.080209
form_field24      23.721321
form_field25       9.727663
form_field26      13.260586
form_field27      16.599515
form_field28       0.623018
form_field29       0.623018
form_field30      45.605298
form_field31      70.378661
form_field32       9.727663
form_field33       2.232792
form_field34       0.623018
form_field35      41.218056
form_field36       3.559037
form_field37       9.727663
form_field38       0.623018
form_field39       7.507928
form_field40      78.086178
form_field41      68.241000
form_field42       2.370826
form_field43       1.007275
form_field44       9.608282
form_field45      56.026861
form_field46      28.427532
form_field47       0.001865
form_field48      37.179631
form_field49       0.623018
form_field50      19.682895
default_status     0.001865
dtype: float64

In [8]:
train_df.drop(['form_field40', 'form_field31','form_field41','form_field11', 'form_field45', 'form_field23'],
              axis=1, inplace = True)
test.drop(['form_field40', 'form_field31','form_field41','form_field11', 'form_field45', 'form_field23'],axis=1, inplace = True)

In [9]:
train_df.drop(['Applicant_ID'], inplace=True, axis=1)
test.drop(['Applicant_ID'], inplace=True, axis=1)

In [10]:
train_df["form_field47"]= train_df["form_field47"].fillna(train_df["form_field47"].value_counts().index[0])
train_df["form_field47"].isnull().sum()

0

In [11]:
train_df["default_status"]= train_df["default_status"].fillna(train_df["default_status"].value_counts().index[0])
train_df["default_status"].isnull().sum()

0

In [12]:
test["form_field47"]= test["form_field47"].fillna(test["form_field47"].value_counts().index[0])
test["form_field47"].isnull().sum()

0

In [13]:
product = {'charge':1, 'lending':0}
default = {'yes':1, 'no':0}
train_df['default_status'].replace(default, inplace=True)
train_df['form_field47'].replace(product, inplace=True)
test['form_field47'].replace(product, inplace=True)

In [14]:
def fill(i):
    for i in train_df:
        if train_df[i].dtype == "float64" or train_df[i].dtype == "int64":
            train_df[i] = train_df[i].fillna(-99999)

In [15]:
def fill(i):
    for i in test:
        if test[i].dtype == "float64" or test[i].dtype == "int64":
            test[i] = test[i].fillna(-99999)

In [16]:
train_df.apply(fill)

form_field1       None
form_field2       None
form_field3       None
form_field4       None
form_field5       None
form_field6       None
form_field7       None
form_field8       None
form_field9       None
form_field10      None
form_field12      None
form_field13      None
form_field14      None
form_field15      None
form_field16      None
form_field17      None
form_field18      None
form_field19      None
form_field20      None
form_field21      None
form_field22      None
form_field24      None
form_field25      None
form_field26      None
form_field27      None
form_field28      None
form_field29      None
form_field30      None
form_field32      None
form_field33      None
form_field34      None
form_field35      None
form_field36      None
form_field37      None
form_field38      None
form_field39      None
form_field42      None
form_field43      None
form_field44      None
form_field46      None
form_field47      None
form_field48      None
form_field49      None
form_field50      None
default_status    None
dtype: object

In [17]:
train_df.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field42,form_field43,form_field44,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
0,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,2301324.0,7875694.0,96375139,112181765.0,1.0,1.0,1.0,3.0,3.0,134.655,NaN,134.655,4000.5,17064.0,11376.0,60.0,17064.0,5962.0,1052.0,8.0000,2.0,NaN,12.0,12.0,4.0,0.0,0.392854,2.02,0.711632,0.0,1,NaN,1.129518,0.044335,0
1,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,3982971.0,2141445.0,28141427,45169902.0,1.0,1.0,1.0,2.0,2.0,109.230,11385.24,86.685,4161.0,13413.0,8942.0,304.0,13413.0,5780.0,2554.0,17.5000,0.0,0.0,16.0,24.0,8.0,0.0,0.314281,8.08,0.183584,0.0,1,349.805730,1.620483,0.322436,0
2,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,1079864.0,NaN,0.0,16576457,22452691.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1597.5,4746.0,3164.0,60.0,15696.0,NaN,70.0,0.6666,0.0,NaN,12.0,0.0,6.0,0.0,0.162965,18.18,0.791136,0.0,1,NaN,1.513370,0.011640,1
3,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,771776.0,1186839.0,48187375,136297820.0,0.0,0.0,0.0,1.0,1.0,120.120,8580.00,85.800,1701.0,4014.0,2676.0,60.0,11679.0,NaN,522.0,7.8334,1.0,1.0,4.0,8.0,4.0,1.0,0.488884,2.02,0.685168,0.0,1,89.940100,0.664452,0.082729,0
4,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,818456.0,511535.0,28141427,15292757.0,0.0,0.0,0.0,3.0,3.0,104.535,8360.19,115.335,1551.0,3285.0,2190.0,60.0,19437.0,12958.0,272.0,1.0000,0.0,0.0,24.0,2.0,24.0,0.0,0.275000,12.12,0.438168,0.0,1,97.887502,1.427891,0.045630,0

In [18]:
test.apply(fill)

form_field1     None
form_field2     None
form_field3     None
form_field4     None
form_field5     None
form_field6     None
form_field7     None
form_field8     None
form_field9     None
form_field10    None
form_field12    None
form_field13    None
form_field14    None
form_field15    None
form_field16    None
form_field17    None
form_field18    None
form_field19    None
form_field20    None
form_field21    None
form_field22    None
form_field24    None
form_field25    None
form_field26    None
form_field27    None
form_field28    None
form_field29    None
form_field30    None
form_field32    None
form_field33    None
form_field34    None
form_field35    None
form_field36    None
form_field37    None
form_field38    None
form_field39    None
form_field42    None
form_field43    None
form_field44    None
form_field46    None
form_field47    None
form_field48    None
form_field49    None
form_field50    None
dtype: object

In [19]:
test.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,form_field12,form_field13,form_field14,form_field15,form_field16,form_field17,form_field18,form_field19,form_field20,form_field21,form_field22,form_field24,form_field25,form_field26,form_field27,form_field28,form_field29,form_field30,form_field32,form_field33,form_field34,form_field35,form_field36,form_field37,form_field38,form_field39,form_field42,form_field43,form_field44,form_field46,form_field47,form_field48,form_field49,form_field50
0,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,0.0,5446.0,0.0,48187375,114686147.0,0.0,0.0,0.0,0.0,0.0,-99999.000,-99999.00,-99999.000,1086.0,6204.0,2676.0,60.0,14691.0,9794.0,238.0,1.8334,0.0,-99999.0,22.0,2.0,14.0,0.0,0.825000,1.01,0.800000,0.0,1,-99999.000000,0.000000,0.011221
1,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,18308285.0,1025793.0,1396510.0,34694910,87479487.0,1.0,1.0,1.0,2.0,2.0,142.560,-99999.00,570.585,3082.5,10221.0,6814.0,60.0,11955.0,3528.0,1216.0,19.5000,3.0,-99999.0,30.0,18.0,14.0,2.0,0.507694,4.04,0.623248,0.0,0,-99999.000000,0.504974,0.043525
2,-99999.0,0.27505,0.0600,0.0000,0.0,-99999.0,-99999.0,-99999.0,-99999.0,0.0,-99999.0,-99999.0,21973443,-99999.0,-99999.0,-99999.0,-99999.0,0.0,0.0,-99999.000,-99999.00,-99999.000,-99999.0,-99999.0,-99999.0,852.0,4836.0,-99999.0,-99999.0,7.8334,0.0,-99999.0,2.0,-99999.0,0.0,-99999.0,-99999.000000,0.00,-99999.000000,-99999.0,1,-99999.000000,0.000000,-99999.000000
3,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,493641.0,1176725.0,1220293.0,16576457,-99999.0,2.0,2.0,2.0,3.0,3.0,109.005,13050.00,109.005,1414.5,4197.0,2798.0,60.0,14964.0,-99999.0,248.0,9.0000,1.0,1.0,36.0,0.0,26.0,0.0,0.916663,2.02,0.464224,-99999.0,1,90.163742,0.788809,0.104029
4,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,5752921.0,613064.0,4779643.0,48187375,72049802.0,0.0,0.0,0.0,3.0,3.0,139.065,469.29,15.180,2724.0,9855.0,6570.0,182.0,11679.0,5900.0,2388.0,16.6666,1.0,0.0,24.0,28.0,20.0,0.0,0.234047,23.23,0.726688,0.0,0,1303.587148,1.637733,0.163124

In [20]:
train_df.isnull().sum()

form_field1        2431
form_field2        3662
form_field3         333
form_field4         333
form_field5         333
form_field6       12775
form_field7        4936
form_field8       12775
form_field9        7650
form_field10        333
form_field12       9447
form_field13       5673
form_field14          0
form_field15      21490
form_field16      12467
form_field17      10662
form_field18       9942
form_field19          0
form_field20        333
form_field21      15142
form_field22      19463
form_field24      12717
form_field25       5215
form_field26       7109
form_field27       8899
form_field28        334
form_field29        334
form_field30      24449
form_field32       5215
form_field33       1197
form_field34        334
form_field35      22097
form_field36       1908
form_field37       5215
form_field38        334
form_field39       4025
form_field42       1271
form_field43        540
form_field44       5151
form_field46      15240
form_field47          0
form_field48      19932
form_field49        334
form_field50      10552
default_status        0
dtype: int64

In [21]:
X = train_df.drop(["default_status"], 1)
X_copy = X.copy()
y = train_df["default_status"]

In [22]:
features = list(X_copy.columns)

In [23]:
train_df["form_field47"].value_counts()

1    34866
0    18744
Name: form_field47, dtype: int64

In [25]:
features = list(X_copy.columns)

In [26]:
cat_features = ["form_field47"]

In [27]:
def metric(y, pred):
    return roc_auc_score(y, pred, labels=[0,1])

In [32]:
# from sklearn.model_selection import cross_validate, train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from catboost import CatBoostClassifier
from sklearn.metrics import log_loss, roc_auc_score


n_skf = 5
score_list = []
score=0
test_oofs = []

from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5)

skf.get_n_splits(X, y)
print(skf)
# StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    
    
    model_cb = CatBoostClassifier(n_estimators = 4000, random_seed = 2020,learning_rate = 0.01, max_depth = 8,
                              eval_metric = "AUC", verbose = 100 , loss_function = "Logloss", objective ="CrossEntropy",
                                  early_stopping_rounds = 200, use_best_model = True)
                                
    
    model_cb.fit(X_train, y_train, eval_set = (X_test, y_test), use_best_model = True, verbose = 100)
    
    
    p = model_cb.predict_proba(X_test)[:, 1]
    
    sc = metric(y_test, p)
    score_list.append(sc)
    score+= sc/n_skf
    
    pred = model_cb.predict_proba(test[features])[:, 1]
    test_oofs.append(pred)
#     print('Fold {} : {}'. format(i, sc))
    
print()
print()
# print('Avg log :', score)    
#   X_train, y_train = X.loc[tr_idx, features], y.loc[tr_idx]
# #     xval, yval = X.loc[vr_idx, features], y.loc[vr_idx]

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)
TRAIN: [10722 10723 10724 ... 53607 53608 53609] TEST: [    0     1     2 ... 10719 10720 10721]
0:	test: 0.8051894	best: 0.8051894 (0)	total: 89ms	remaining: 5m 55s
100:	test: 0.8254673	best: 0.8254673 (100)	total: 8.23s	remaining: 5m 17s
200:	test: 0.8287414	best: 0.8287414 (200)	total: 16.2s	remaining: 5m 6s
300:	test: 0.8305385	best: 0.8305385 (300)	total: 23.8s	remaining: 4m 53s
400:	test: 0.8318955	best: 0.8318955 (400)	total: 32.5s	remaining: 4m 51s
500:	test: 0.8331022	best: 0.8331022 (500)	total: 40.1s	remaining: 4m 39s
600:	test: 0.8338965	best: 0.8338984 (597)	total: 47.6s	remaining: 4m 29s
700:	test: 0.8344899	best: 0.8344899 (700)	total: 55.2s	remaining: 4m 19s
800:	test: 0.8349787	best: 0.8349787 (800)	total: 1m 2s	remaining: 4m 10s
900:	test: 0.8354078	best: 0.8354078 (900)	total: 1m 10s	remaining: 4m 1s
1000:	test: 0.8358092	best: 0.8358092 (1000)	total: 1m 17s	remaining: 3m 53s
1100:	test: 0.8362247	best: 0.8362345 (1096)	total: 1m 25s	remaining: 3m 44s
1200:	test: 0.8365560	best: 0.8365613 (1199)	total: 1m 33s	remaining: 3m 37s
1300:	test: 0.8368227	best: 0.8368227 (1300)	total: 1m 40s	remaining: 3m 29s
1400:	test: 0.8370141	best: 0.8370141 (1400)	total: 1m 48s	remaining: 3m 21s
1500:	test: 0.8370444	best: 0.8370678 (1426)	total: 1m 55s	remaining: 3m 12s
1600:	test: 0.8370604	best: 0.8370885 (1567)	total: 2m 3s	remaining: 3m 4s
1700:	test: 0.8371471	best: 0.8371512 (1699)	total: 2m 10s	remaining: 2m 56s
1800:	test: 0.8371386	best: 0.8371877 (1741)	total: 2m 18s	remaining: 2m 49s
1900:	test: 0.8370790	best: 0.8371877 (1741)	total: 2m 26s	remaining: 2m 41s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8371876711
bestIteration = 1741

Shrink model to first 1742 iterations.
TRAIN: [    0     1     2 ... 53607 53608 53609] TEST: [10722 10723 10724 ... 21519 21522 21523]
0:	test: 0.8033140	best: 0.8033140 (0)	total: 108ms	remaining: 7m 11s
100:	test: 0.8293100	best: 0.8293100 (100)	total: 8.54s	remaining: 5m 29s
200:	test: 0.8335894	best: 0.8335894 (200)	total: 16.3s	remaining: 5m 7s
300:	test: 0.8359276	best: 0.8359276 (300)	total: 23.9s	remaining: 4m 53s
400:	test: 0.8375764	best: 0.8375764 (400)	total: 31.4s	remaining: 4m 41s
500:	test: 0.8386303	best: 0.8386356 (499)	total: 39s	remaining: 4m 32s
600:	test: 0.8393294	best: 0.8393343 (599)	total: 46.6s	remaining: 4m 23s
700:	test: 0.8398558	best: 0.8398558 (700)	total: 54.2s	remaining: 4m 15s
800:	test: 0.8403065	best: 0.8403079 (792)	total: 1m 1s	remaining: 4m 7s
900:	test: 0.8406257	best: 0.8406268 (897)	total: 1m 9s	remaining: 3m 59s
1000:	test: 0.8408817	best: 0.8408821 (999)	total: 1m 17s	remaining: 3m 51s
1100:	test: 0.8412093	best: 0.8412093 (1100)	total: 1m 25s	remaining: 3m 43s
1200:	test: 0.8414448	best: 0.8414448 (1200)	total: 1m 32s	remaining: 3m 35s
1300:	test: 0.8416578	best: 0.8416578 (1300)	total: 1m 40s	remaining: 3m 27s
1400:	test: 0.8416864	best: 0.8416982 (1333)	total: 1m 48s	remaining: 3m 20s
1500:	test: 0.8418550	best: 0.8418550 (1500)	total: 1m 55s	remaining: 3m 12s
1600:	test: 0.8419727	best: 0.8419801 (1593)	total: 2m 3s	remaining: 3m 4s
1700:	test: 0.8420351	best: 0.8420783 (1662)	total: 2m 10s	remaining: 2m 56s
1800:	test: 0.8419940	best: 0.8420783 (1662)	total: 2m 18s	remaining: 2m 49s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8420783091
bestIteration = 1662

Shrink model to first 1663 iterations.
TRAIN: [    0     1     2 ... 53607 53608 53609] TEST: [21260 21262 21268 ... 32377 32380 32381]
0:	test: 0.8064707	best: 0.8064707 (0)	total: 123ms	remaining: 8m 13s
100:	test: 0.8264659	best: 0.8264659 (100)	total: 8.51s	remaining: 5m 28s
200:	test: 0.8300387	best: 0.8300387 (200)	total: 16.2s	remaining: 5m 6s
300:	test: 0.8324163	best: 0.8324163 (300)	total: 23.8s	remaining: 4m 52s
400:	test: 0.8339386	best: 0.8339386 (400)	total: 31.3s	remaining: 4m 41s
500:	test: 0.8352468	best: 0.8352468 (500)	total: 39.4s	remaining: 4m 35s
600:	test: 0.8360394	best: 0.8360394 (600)	total: 47s	remaining: 4m 25s
700:	test: 0.8366730	best: 0.8366730 (700)	total: 54.6s	remaining: 4m 16s
800:	test: 0.8370480	best: 0.8370534 (796)	total: 1m 2s	remaining: 4m 8s
900:	test: 0.8373494	best: 0.8373494 (900)	total: 1m 9s	remaining: 4m
1000:	test: 0.8377256	best: 0.8377256 (1000)	total: 1m 17s	remaining: 3m 53s
1100:	test: 0.8381122	best: 0.8381162 (1099)	total: 1m 25s	remaining: 3m 45s
1200:	test: 0.8382429	best: 0.8382452 (1198)	total: 1m 33s	remaining: 3m 36s
1300:	test: 0.8384654	best: 0.8384669 (1298)	total: 1m 40s	remaining: 3m 28s
1400:	test: 0.8386516	best: 0.8386544 (1398)	total: 1m 48s	remaining: 3m 20s
1500:	test: 0.8386560	best: 0.8387187 (1436)	total: 1m 55s	remaining: 3m 12s
1600:	test: 0.8387069	best: 0.8387277 (1591)	total: 2m 3s	remaining: 3m 4s
1700:	test: 0.8386946	best: 0.8387581 (1673)	total: 2m 11s	remaining: 2m 57s
1800:	test: 0.8386814	best: 0.8387581 (1673)	total: 2m 18s	remaining: 2m 49s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8387581269
bestIteration = 1673

Shrink model to first 1674 iterations.
TRAIN: [    0     1     2 ... 53607 53608 53609] TEST: [31482 31483 31487 ... 43319 43320 43321]
0:	test: 0.8025282	best: 0.8025282 (0)	total: 141ms	remaining: 9m 24s
100:	test: 0.8207899	best: 0.8207899 (100)	total: 8.56s	remaining: 5m 30s
200:	test: 0.8247392	best: 0.8247392 (200)	total: 16.3s	remaining: 5m 7s
300:	test: 0.8270674	best: 0.8270674 (300)	total: 24s	remaining: 4m 54s
400:	test: 0.8282761	best: 0.8282761 (400)	total: 31.7s	remaining: 4m 44s
500:	test: 0.8293837	best: 0.8293837 (500)	total: 39.4s	remaining: 4m 35s
600:	test: 0.8301213	best: 0.8301244 (595)	total: 47.1s	remaining: 4m 26s
700:	test: 0.8305541	best: 0.8305541 (700)	total: 55s	remaining: 4m 18s
800:	test: 0.8309140	best: 0.8309140 (800)	total: 1m 2s	remaining: 4m 9s
900:	test: 0.8313028	best: 0.8313220 (893)	total: 1m 10s	remaining: 4m 1s
1000:	test: 0.8314883	best: 0.8314883 (1000)	total: 1m 17s	remaining: 3m 53s
1100:	test: 0.8315940	best: 0.8316069 (1077)	total: 1m 25s	remaining: 3m 45s
1200:	test: 0.8318028	best: 0.8318028 (1200)	total: 1m 33s	remaining: 3m 37s
1300:	test: 0.8320672	best: 0.8320691 (1296)	total: 1m 40s	remaining: 3m 29s
1400:	test: 0.8320599	best: 0.8321148 (1388)	total: 1m 48s	remaining: 3m 20s
1500:	test: 0.8321250	best: 0.8321442 (1482)	total: 1m 55s	remaining: 3m 13s
1600:	test: 0.8321033	best: 0.8321442 (1520)	total: 2m 3s	remaining: 3m 5s
1700:	test: 0.8322635	best: 0.8322704 (1699)	total: 2m 11s	remaining: 2m 57s
1800:	test: 0.8322107	best: 0.8322740 (1719)	total: 2m 18s	remaining: 2m 49s
1900:	test: 0.8321548	best: 0.8322740 (1719)	total: 2m 26s	remaining: 2m 41s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.832273974
bestIteration = 1719

Shrink model to first 1720 iterations.
TRAIN: [    0     1     2 ... 43319 43320 43321] TEST: [41377 41379 41380 ... 53607 53608 53609]
0:	test: 0.8180290	best: 0.8180290 (0)	total: 86.2ms	remaining: 5m 44s
100:	test: 0.8359891	best: 0.8359891 (100)	total: 8.52s	remaining: 5m 28s
200:	test: 0.8397468	best: 0.8397468 (200)	total: 16.2s	remaining: 5m 6s
300:	test: 0.8417051	best: 0.8417067 (299)	total: 24.1s	remaining: 4m 55s
400:	test: 0.8428116	best: 0.8428116 (400)	total: 31.9s	remaining: 4m 46s
500:	test: 0.8436870	best: 0.8436870 (500)	total: 39.6s	remaining: 4m 36s
600:	test: 0.8442176	best: 0.8442176 (600)	total: 47.1s	remaining: 4m 26s
700:	test: 0.8446412	best: 0.8446412 (700)	total: 54.8s	remaining: 4m 17s
800:	test: 0.8449943	best: 0.8449943 (800)	total: 1m 2s	remaining: 4m 9s
900:	test: 0.8452732	best: 0.8452801 (899)	total: 1m 9s	remaining: 4m
1000:	test: 0.8454999	best: 0.8455248 (992)	total: 1m 17s	remaining: 3m 52s
1100:	test: 0.8455529	best: 0.8455965 (1092)	total: 1m 25s	remaining: 3m 43s
1200:	test: 0.8456270	best: 0.8456407 (1159)	total: 1m 32s	remaining: 3m 35s
1300:	test: 0.8456612	best: 0.8457152 (1274)	total: 1m 40s	remaining: 3m 27s
1400:	test: 0.8457225	best: 0.8457409 (1342)	total: 1m 47s	remaining: 3m 20s
1500:	test: 0.8455443	best: 0.8457409 (1342)	total: 1m 55s	remaining: 3m 12s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8457409095
bestIteration = 1342

Shrink model to first 1343 iterations.

In [33]:
f'{n_skf} fold CV, score: {score}'

'5 fold CV, score: 0.8392077980997802'

In [34]:
oof_prediction = pd.DataFrame(test_oofs).T
oof_prediction

              0         1         2         3         4
0      0.370287  0.359021  0.342569  0.369045  0.289124
1      0.296276  0.300804  0.374475  0.302063  0.306425
2      0.405364  0.482913  0.489426  0.525462  0.408696
3      0.755106  0.771602  0.739862  0.769687  0.762258
4      0.176547  0.165075  0.174250  0.133676  0.199447
5      0.434114  0.517652  0.504782  0.561788  0.440240
6      0.384197  0.417606  0.399358  0.452488  0.374734
7      0.571710  0.578477  0.532681  0.580458  0.593888
8      0.464359  0.454186  0.364123  0.413266  0.395816
9      0.366422  0.353140  0.358814  0.336768  0.369288
10     0.113608  0.113420  0.109201  0.111716  0.119635
11     0.018470  0.023686  0.018968  0.019146  0.021082
12     0.600050  0.597053  0.589373  0.628886  0.605723
13     0.042701  0.040095  0.044303  0.046626  0.046920
14     0.448429  0.459154  0.506767  0.490788  0.447409
15     0.705631  0.654172  0.630612  0.726743  0.622837
16     0.318782  0.339844  0.308380  0.332527  0.321923
17     0.070226  0.064077  0.067788  0.062497  0.067026
18     0.126436  0.111930  0.130711  0.128549  0.127437
19     0.766372  0.728917  0.789001  0.757342  0.752944
20     0.056066  0.066008  0.075353  0.066248  0.078750
21     0.091590  0.095015  0.098644  0.083002  0.084630
22     0.061138  0.048949  0.053681  0.058584  0.051300
23     0.295047  0.276169  0.299370  0.281047  0.353479
24     0.022107  0.025654  0.022449  0.023039  0.029827
25     0.036409  0.044232  0.032920  0.039895  0.034949
26     0.577352  0.469194  0.569645  0.527350  0.458192
27     0.041847  0.052395  0.040332  0.049892  0.043072
28     0.147653  0.162993  0.152834  0.148705  0.151693
29     0.087317  0.082184  0.082760  0.078005  0.077011
...         ...       ...       ...       ...       ...
23970  0.431946  0.439446  0.457594  0.456343  0.423792
23971  0.305223  0.300886  0.317946  0.307260  0.297638
23972  0.113400  0.117141  0.118311  0.115970  0.128438
23973  0.015738  0.014422  0.015032  0.011922  0.016077
23974  0.119637  0.147239  0.128284  0.125848  0.120881
23975  0.161352  0.121077  0.148775  0.180181  0.135505
23976  0.010175  0.010002  0.010313  0.011585  0.010304
23977  0.079328  0.071351  0.079734  0.069459  0.062280
23978  0.014632  0.014181  0.016847  0.015640  0.015361
23979  0.495471  0.476873  0.483282  0.522825  0.470737
23980  0.046729  0.054715  0.053522  0.044075  0.045632
23981  0.470130  0.438295  0.481972  0.470643  0.432527
23982  0.418540  0.384020  0.368076  0.395417  0.331543
23983  0.599454  0.569027  0.596707  0.562964  0.572254
23984  0.488170  0.488549  0.475323  0.489269  0.507257
23985  0.331640  0.379579  0.339176  0.427410  0.278074
23986  0.581009  0.548362  0.616363  0.594914  0.591907
23987  0.289525  0.365437  0.325184  0.346303  0.333023
23988  0.485317  0.483465  0.574166  0.582255  0.516458
23989  0.043613  0.041905  0.039836  0.036537  0.039796
23990  0.462982  0.491478  0.458624  0.477198  0.438217
23991  0.716905  0.733730  0.718395  0.758274  0.702519
23992  0.801076  0.805866  0.827913  0.837142  0.796317
23993  0.604529  0.644167  0.629064  0.656811  0.678011
23994  0.143974  0.133412  0.132190  0.126334  0.131042
23995  0.666129  0.665445  0.629155  0.663036  0.648556
23996  0.278882  0.238083  0.278520  0.285862  0.296817
23997  0.335742  0.334709  0.365082  0.306341  0.356077
23998  0.542428  0.528401  0.537026  0.587756  0.535067
23999  0.195529  0.260984  0.226977  0.188298  0.218542

[24000 rows x 5 columns]

In [35]:
oof_prediction.columns = ['fold' +str(i) for i in range(1, n_skf + 1)]

In [36]:

sub['default_status'] = np.mean(test_oofs, axis=0)

In [37]:

sub.to_csv('fourth1_submission.csv', index=False)